---
- name: Configure Consul integration
  ansible.builtin.import_tasks: consul_integration.yml
  when:
    - ansible_hostname in groups['servers']
  delegate_to: "{{ groups['servers'][0] }}"
  run_once: true

- name: Configure Nomad service
  ansible.builtin.import_tasks: configure.yml

- name: Bootstrap Nomad ACL
  ansible.builtin.import_tasks: acl_bootstrap.yml
  when:
    - ansible_hostname in groups['servers']
  delegate_to: "{{ groups['servers'][0] }}"
  run_once: true

- name: Configure Vault integration
  ansible.builtin.import_tasks: vault_integration.yml
  when:
    - ansible_hostname in groups['servers']
  delegate_to: "{{ groups['servers'][0] }}"
  run_once: true
