---
- name: Load Vault credentials
  block:
    - name: Read Vault's initialization data
      ansible.builtin.shell: "cat vault-init.token"
      register: vault_init_output
      delegate_to: localhost
      become: false

    - name: Set Vault's initialization data fact
      ansible.builtin.set_fact:
        vault_init: "{{ (vault_init_output.stdout | from_json) }}"

- name: Unseal Vault
  ansible.builtin.command: "vault operator unseal {{ item }}"
  environment:
    VAULT_ADDR: "http://localhost:8200"
  loop: "{{ vault_init.unseal_keys_b64 }}"

- name: Configure Nomad's Vault access
  block:
    - name: Enable JWT auth
      ansible.builtin.uri:
        url: "http://localhost:8200/v1/sys/auth/jwt-nomad"
        method: POST
        body_format: json
        body:
          type: "jwt"
          description: "JWT auth backend for Nomad"
        headers:
          X-Vault-Token: "{{ vault_init.root_token }}"
        status_code: 
          - 200
          - 204

    - name: Create Nomad's Vault auth backend
      ansible.builtin.uri:
        url: "http://localhost:8200/v1/auth/jwt-nomad/config"
        method: POST
        body_format: json
        body:
          jwks_url: "http://nomad.service.consul:4646/.well-known/jwks.json"
          jwt_supported_algs:
            - "RS256"
            - "EdDSA"
          default_role: "nomad-workloads"
        headers:
          X-Vault-Token: "{{ vault_init.root_token }}"
        status_code:
          - 200
          - 204

    - name: Create Nomad's Vault auth role
      ansible.builtin.uri:
        url: "http://localhost:8200/v1/auth/jwt-nomad/role/nomad-workloads"
        method: POST
        body_format: json
        body:
          role_type: "jwt"
          bound_audiences:
            - "vault.io"
          user_claim: "/nomad_job_id"
          user_claim_json_pointer: true
          claim_mappings:
            nomad_namespace: nomad_namespace
            nomad_job_id: nomad_job_id
            nomad_group: nomad_group
          token_type: "service"
          token_policies:
            - "nomad-workloads"
          token_period: "30m"
          token_explicit_max_ttl: 0
        headers:
          X-Vault-Token: "{{ vault_init.root_token }}"
        status_code:
          - 200
          - 204

    - name: Load Nomad's Vault method's accessor ID
      block:
        - name: Read Nomad's Vault method's configuration
          ansible.builtin.uri:
            url: "http://localhost:8200/v1/sys/auth/jwt-nomad"
            method: GET
            headers:
              X-Vault-Token: "{{ vault_init.root_token }}"
            return_content: true
          register: nomad_vault_method_config_raw

        - name: Set Nomad's Vault method's accessor ID fact
          ansible.builtin.set_fact:
            nomad_vault_method_accessor: "{{ nomad_vault_method_config_raw.json.data.accessor }}"

    - name: Deploy Nomad's Vault policy
      ansible.builtin.template:
        src: vault-nomad-policy.hcl.j2
        dest: "{{ nomad_data_dir }}/vault-nomad-policy.hcl"
        mode: 0644

    - name: Create Nomad's Vault policy
      ansible.builtin.command: >-
        vault policy write
        nomad-workloads
        {{ nomad_data_dir }}/vault-nomad-policy.hcl
      environment:
        VAULT_ADDR: "http://localhost:8200"
        VAULT_TOKEN: "{{ vault_init.root_token }}"

  notify: restart vault
