---
  - name: restart consul
    ansible.builtin.systemd:
      name: consul
      state: restarted

  - name: restart systemd-resolved
    ansible.builtin.systemd:
      name: systemd-resolved
      state: restarted
